Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.synced_folder "../services", "/services"

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox",
        SharedFoldersEnableSymlinksCreate: false

    # Manager node
    config.vm.define "manager01" do |manager|
        manager.vm.hostname = "manager01"
        manager.vm.network "private_network", ip: "192.168.56.10"

        manager.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2

        end
    end

    # Worker nodes
    config.vm.define "node01" do |node|
        node.vm.hostname = "node01"
        node.vm.network "private_network", ip: "192.168.56.11"
        
        node.vm.network "forwarded_port", guest: 8081, host: 8081
        node.vm.network "forwarded_port", guest: 8087, host: 8087 

        node.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 1
        end
    end

    config.vm.define "node02" do |node|
        node.vm.hostname = "node02"
        node.vm.network "private_network", ip: "192.168.56.12"
        node.vm.network "forwarded_port", guest: 80, host: 8080

        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
    end
end