Vagrant.configure("2") do |config|
  # Образ для всех машин (Ubuntu 22.04)
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "./services", "/services"
  
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", 
    SharedFoldersEnableSymlinksCreate: false

  # Настройка менеджера (мастер-узла)
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "0.0.0.0", auto_correct: true
    master.vm.network "forwarded_port", guest: 8087, host: 8087, host_ip: "0.0.0.0", auto_correct: true

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "5120"
      vb.cpus = "3"
    end
  end

  # Настройка первого рабочего узла
  config.vm.define "worker01" do |worker1|
    worker1.vm.hostname = "worker01"
    worker1.vm.network "private_network", ip: "192.168.56.11"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end

  # Настройка второго рабочего узла
  config.vm.define "worker02" do |worker2|
    worker2.vm.hostname = "worker02"
    worker2.vm.network "private_network", ip: "192.168.56.12"
    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
end