{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      enableServiceLinks: false
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .port }}
        env:
        {{- range $key, $value := .env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- range $key, $value := .secrets }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- if eq .name "postgres" }}
        nodeSelector:
          kubernetes.io/hostname: master
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        {{- end }}
      {{- if eq .name "postgres" }}
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      {{- end }}
{{- end }}