apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  {{- range .Values.services }}
  {{- if .secrets }}
  {{- range $key, $value := .secrets }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}
  {{- end }}
