---
# Централизация определения параметров, которые используются в задачах роли
advertise_addr: "{{ ansible_host }}"  # Используем IP из инвентаря
consul_version: "1.22.3"
consul_server_ip: "192.168.56.10"  # IP сервера Consul