apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password" 
  GATEWAY_UUID: "b51ceda2-bfa5-11eb-8529-0242ac130003"
  BOOKING_UUID: "911ccb4c-c055-11eb-8529-0242ac130003"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"