Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./services", "/services"
  
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", 
    SharedFoldersEnableSymlinksCreate: false

  # Manager node
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"

    manager.vm.network "forwarded_port", guest: 8081, host: 8081
    manager.vm.network "forwarded_port", guest: 8087, host: 8087
    manager.vm.network "forwarded_port", guest: 9443, host: 9443

    manager.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    
    manager.vm.provision "shell", path: "scripts/install-docker.sh"
    manager.vm.provision "shell", path: "scripts/init-swarm.sh", run: "always"
  end

  # Worker nodes
  config.vm.define "worker01" do |worker|
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/install-docker.sh"
    worker.vm.provision "shell", path: "scripts/join-swarm.sh", run: "always"
  end

  config.vm.define "worker02" do |worker|
    worker.vm.hostname = "worker02"
    worker.vm.network "private_network", ip: "192.168.56.12"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    
    worker.vm.provision "shell", path: "scripts/install-docker.sh"
    worker.vm.provision "shell", path: "scripts/join-swarm.sh", run: "always"
  end
end