events {
    worker_connections 1024;
}

http {
    # Прокси для session-service
    server {
        listen 8081;
        
        location / {
            proxy_pass http://session-service:8081;
        }
    }
    
    # Прокси для gateway-service  
    server {
        listen 8087;
        
        location / {
            proxy_pass http://gateway-service:8087;
        }
    }
}