Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  
  # Общие настройки
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # 1. Consul сервер
  config.vm.define "consul_server" do |server|
    server.vm.hostname = "consul-server"
    server.vm.network "private_network", ip: "192.168.56.10"
    # Проброс порта для UI Consul
    server.vm.network "forwarded_port", guest: 8500, host: 8500, auto_correct: true
  end

  # 2. API
  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.56.11"
    api.vm.network "forwarded_port", guest: 8082, host: 8082, auto_correct: true
  end

  # 3. Manager
  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.synced_folder "../services/hotel-service", "/vagrant/hotel-service"
    manager.vm.synced_folder "../consul01", "/vagrant/consul01"
    manager.vm.network "private_network", ip: "192.168.56.12"
  end

  # 4. DB
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.13"
  end
end